/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SampleRecipient__factory } from "./SampleRecipient__factory";
export { SingletonFactory__factory } from "./SingletonFactory__factory";
