name: ✨ Feature Requests & Performance Improvements
description: Suggest a new feature or performance enhancement
title: "[FEATURE] "
labels: ["enhancement", "good first issue"]
body:
  - type: markdown
    attributes:
      value: "Your suggestions inspire us to improve. Share your ideas below!"
  - type: input
    attributes:
      label: Feature or Improvement Description
      description: Describe the feature or improvement you're suggesting.
      placeholder: "e.g., Add support for platform Z."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Benefits & Outcomes
      description: Explain the benefits of your suggestion and the expected outcomes.
      placeholder: "This improvement will improve performance by 30%..."
  - type: input
    attributes:
      label: Any References?
      description: Provide links or references to similar features or standards.
      placeholder: "EIP-1234, https://github.com/example"
  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
