name: 🔒 Security Pre-Screening
description: Pre-screening for security-related reports
title: "[SECURITY PRE-SCREEN] "
labels: ["security", "triage needed"]
body:
  - type: markdown
    attributes:
      value: "Security is our top priority. If you've discovered a potential security issue that is **critical or high** in nature and could affect our deployed contracts, **please do not report it here.** Instead, email us directly at security@biconomy.io for a confidential review. For all other security-related inquiries that do not pose an immediate risk to our deployed contracts, please proceed."
  - type: checkboxes
    attributes:
      label: Security Level Acknowledgement
      options:
        - label: "I understand this issue will be public. It is NOT critical or high risk and does not endanger deployed contracts."
          required: true
  - type: input
    attributes:
      label: Overview
      description: Provide a summary of the non-critical security concern or question.
      placeholder: "e.g., Questions about the audit process."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Details
      description: Offer more detail on your concern or question.
      placeholder: "Provide any additional context..."
  - type: input
    attributes:
      label: Suggestions for Mitigation
      description: (Optional) Suggest ways to address the concern.
      placeholder: "Potential mitigation steps include..."
