/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SampleRecipient } from "./SampleRecipient";
export type { SingletonFactory } from "./SingletonFactory";
