import type { AuthModule, UserAuthentication } from './authentication';
import type { IWalletProviderServiceClient } from './walletProviderServiceClientInterface';
/**
 * Response from the network for keygen requests
 * @alpha
 */
export interface KeygenResponse {
    keyId: string;
    publicKey: string;
}
/**
 * Response from the network for sign request
 * @alpha
 */
export interface SignResponse {
    sign: string;
    recid: number;
}
/** Key parameters used during generation  */
export declare class KeygenSetupOpts {
    /** Threshold, number of parties that needs to participate in a protocol in order to produce valid signature */
    t: number;
    /** Total number of nodes that participate in Key generation, must be greater or equal than `t` */
    n: number;
    /** Optional key label */
    key_label?: string;
    /** Metadata for a key. Currently they store the permissions, can be set in a constructor of this class.
      If permissions are not set, all operations are allowed.
     */
    metadata: {
        tag: number;
        value: string;
    }[];
    constructor({ t, n, key_label, permissions, ephPK, }: {
        t: number;
        n: number;
        key_label?: string;
        permissions?: string;
        ephPK?: string;
    });
}
/** Parameters used in Signature execution */
export type SignSetupOpts = {
    /** Nymber of nodes that will participate in the signature execution */
    t: number;
    /** Select the key using it's ID */
    key_id: string;
    /** The message to sign */
    message: string;
};
/** Verifies if passed `params` object is of type SignSetupOpts */
export declare function isSignSetupOpts(params: KeygenSetupOpts | SignSetupOpts): params is SignSetupOpts;
/** The `user_authentication` contains signature over the `setup` parameter. */
export type UserAuthenticatedRequest<T> = {
    setup: T;
    user_authentication: UserAuthentication;
};
/** The networkSigner contains an API to communicate with the Silent MPC Network. Call to sign and keygen require
 * the Auth module, that is used to prompt the User before executing the request.
 * @alpha
 */
export declare class NetworkSigner {
    /** Authentication module, used to get confirmation from the User before request execution */
    authModule: AuthModule;
    /** Number of nodes that needs to participate in protocol in order to generate valid signature. Also known as `t`. */
    threshold: number;
    /** Number of nodes that participate in keygen operation. Also known as `n`. */
    totalNodes: number;
    /** Wallet Provider backend client */
    wp_client: IWalletProviderServiceClient;
    /**
     * Facade class used to execute operations on Silent Network.
     * @param wpClient - Wallet Provider backend client
     * @param threshold - Number of nodes that needs to participate in protocol in order to generate valid signature. Also known as `t`.
     * @param totalNodes - Number of nodes that participate in keygen operation. Also known as `n`.
     * @param authModule - Authentication module, used to get confirmation from the User before request execution
     */
    constructor(wpClient: IWalletProviderServiceClient, threshold: number, totalNodes: number, authModule: AuthModule);
    /** API to generate a delegated key that's generated by Silent Network.
     * Uses `authModule` to get authentication of the request from the User
     * @param ephKey - ephemeral key used to authenticate the user during the session.
     * @param permissions - optional permissions that will be stored in the key metadata.
     * The permissions are validated during sign requests.
     * @returns {@link KeygenResponse} containing `keyId` and the `pubKey` public part of the key
     * @public
     * @alpha
     */
    authenticateAndCreateKey(ephKey: Uint8Array, permissions?: string): Promise<KeygenResponse>;
    /** Generate a signature. Uses `authModule` to authenticate the sign request by the User.
     * The network chooses `t` nodes to execute the protocol.
     * @param keyId - the key id returned from `authenticateAndCreateKey`
     * @param message - the message to sign by the MPC network
     * @returns {@link SignResponse}
     * @public
     * @alpha
     */
    authenticateAndSign(keyId: string, message: string): Promise<SignResponse>;
}
//# sourceMappingURL=networkSigner.d.ts.map