import { ethers, BigNumber } from 'ethers'


export type Bundlerconfig = {
    bundlerUrl: string,
    epAddress: string
}

export type UserOpReceipt = {
  userOpHash: string,
  entryPoint: string,
  sender: string,
  nonce: number,
  paymaster: string,
  actualGasCost: BigNumber,
  actualGasUsed: BigNumber,
  success: boolean,
  reason: string,
  logs:  Array<ethers.providers.Log>, // The logs generated by this UserOperation (not including logs of other UserOperations in the same bundle)
  receipt: ethers.providers.TransactionReceipt
}

export type UserOpResponse = {
  result: string,
  wait(confirmations?: number): Promise<UserOpReceipt>
}

export type UserOpGasFieldsResponse = {
  result: {
    preVerificationGas: string
    verificationGasLimit: string
    callGasLimit: string
    maxPriorityFeePerGas: string
    maxFeePerGas: string
    gasPrice: string
  }
}
