name: coverage
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
jobs:
  coverage:
    name: coverage
    permissions: write-all
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4


      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run the tests
        run: bun run test --coverage
        env:
          E2E_PRIVATE_KEY_ONE: ${{ secrets.E2E_PRIVATE_KEY_ONE }}
          BUNDLER_URL: https://api.pimlico.io/v2/84532/rpc?apikey=pim_im13GpaqtMDSiJFhXMxcVn
          CHAIN_ID: 84532
          CI: true 

      - name: report coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: ./coverage/coverage-summary.json
          json-final-path: "./coverage/coverage-final.json"
          vite-config-path: ./tests/vitest.config.ts
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          slug: bcnmy/biconomy-client-sdk
