name: playground
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  playground:
    name: playground
    permissions: write-all
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-playground
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run the account tests
        run: RUN_PLAYGROUND=true bun run test:ci -t=Playground
        env:
          E2E_PRIVATE_KEY_ONE: ${{ secrets.E2E_PRIVATE_KEY_ONE }}
          BUNDLER_URL: https://api.pimlico.io/v2/84532/rpc?apikey=pim_im13GpaqtMDSiJFhXMxcVn
          CHAIN_ID: 84532
